# Generated by Django 6.1.1 on 2026-09-25 17:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(verbose_name='Title')),
                ('Provider', models.CharField(verbose_name='Provider')),
                ('date_recieved', models.DateField(default=django.utils.timezone.localdate, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.localdate)], verbose_name='Date Recieved')),
                ('Proof', models.FileField(upload_to='certificate/', verbose_name='Proof')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Certificate',
            },
        ),
        migrations.CreateModel(
            name='DailyJournel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.localdate, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.localdate)], verbose_name='Date')),
                ('Time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='Time')),
                ('One_word_to_describe_the_day', models.CharField(max_length=50, verbose_name='One word to describe the day')),
                ('Journel', models.TextField(verbose_name='Journel')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Daily Journels',
            },
        ),
        migrations.CreateModel(
            name='MovieAndSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(verbose_name='Name')),
                ('Status', models.CharField(choices=[('Plan to watch', 'Plan to watch'), ('watching', 'watching'), ('completed', 'completed')], verbose_name='Status')),
                ('Content_type', models.CharField(choices=[('movie', 'movie'), ('show', 'show')], verbose_name='Content Type')),
                ('Anime', models.BooleanField(verbose_name='Anime')),
                ('Note', models.TextField(blank=True, verbose_name='Note')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Movies and Series',
            },
        ),
        migrations.CreateModel(
            name='SiteDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200,blank=False, verbose_name='Site Name')),
                ('Site_url', models.URLField(max_length=1000,blank=False,unique=True, verbose_name='Site URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discovered_on', models.DateField(default=django.utils.timezone.localdate, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.localdate)], verbose_name='Discovered On')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Sites Discovery',
            },
        ),
    ]
