# Generated by Django 6.1.1 on 2026-09-12 03:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField()),
                ('Provider', models.CharField()),
                ('date_recieved', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 9, 12))])),
                ('Proof', models.FileField(upload_to='certificate/')),
            ],
        ),
        migrations.CreateModel(
            name='MovieAndSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Status', models.CharField(choices=[('Plan to watch', 'Plan to watch'), ('watching', 'watching'), ('completed', 'completed')])),
                ('Content_type', models.CharField(choices=[('movie', 'movie'), ('show', 'show')])),
                ('Anime', models.BooleanField()),
                ('Note', models.TextField()),
            ],
        ),
    ]
