# Generated by Django 6.1.1 on 2026-09-24 01:13

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(verbose_name='Title')),
                ('Provider', models.CharField(verbose_name='Provider')),
                ('date_recieved', models.DateField(default=django.utils.timezone.localdate, validators=[django.core.validators.MaxValueValidator(django.utils.timezone.localdate)], verbose_name='Date Recieved')),
                ('Proof', models.FileField(upload_to='certificate/', verbose_name='Proof')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Certificate',
            },
        ),
        migrations.CreateModel(
            name='MovieAndSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(verbose_name='Name')),
                ('Status', models.CharField(choices=[('Plan to watch', 'Plan to watch'), ('watching', 'watching'), ('completed', 'completed')], verbose_name='Status')),
                ('Content_type', models.CharField(choices=[('movie', 'movie'), ('show', 'show')], verbose_name='Content Type')),
                ('Anime', models.BooleanField(verbose_name='Anime')),
                ('Note', models.TextField(blank=True, verbose_name='Note')),
                ('User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Movies and Series',
            },
        ),
    ]
