# Generated by Django 6.1.1 on 2026-09-16 02:54

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate'},
        ),
        migrations.AlterModelOptions(
            name='movieandseries',
            options={'verbose_name_plural': 'Movies and Series'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Proof',
            field=models.FileField(upload_to='certificate/', verbose_name='Proof'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Provider',
            field=models.CharField(verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Title',
            field=models.CharField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_recieved',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 9, 16))], verbose_name='Date Recieved'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieandseries',
            name='Anime',
            field=models.BooleanField(verbose_name='Anime'),
        ),
        migrations.AlterField(
            model_name='movieandseries',
            name='Content_type',
            field=models.CharField(choices=[('movie', 'movie'), ('show', 'show')], verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='movieandseries',
            name='Name',
            field=models.CharField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movieandseries',
            name='Note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='movieandseries',
            name='Status',
            field=models.CharField(choices=[('Plan to watch', 'Plan to watch'), ('watching', 'watching'), ('completed', 'completed')], verbose_name='Status'),
        ),
    ]
