# Generated by Django 6.1.1 on 2026-09-16 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False),
        ),
    ]
