# Generated by Django 6.1.1 on 2026-09-16 19:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_recieved',
            field=models.DateField(default=datetime.date(2026, 9, 17), validators=[django.core.validators.MaxValueValidator(datetime.date(2026, 9, 17))], verbose_name='Date Recieved'),
        ),
    ]
